/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "svwmgzzigbhtdeabplxm"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2d21nenppZ2JodGRlYWJwbHhtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzA1MzM2MzksImV4cCI6MjA4NjEwOTYzOX0.HUOwczZSM6kb-gxFo3BW0xHkKbSX6aUbBr2Waew-EHc"